#!/bin/bash -e

realhome=$(getent passwd $UID | cut -d ':' -f 6)

# link host's ssh config if it exists

host_ssh="$realhome/.ssh"
snap_ssh="$HOME/.ssh"

rm -rf "$snap_ssh"

if [ -d "$host_ssh" ]; then
  mkdir -m 0700 "$snap_ssh"
fi

# import ssh keys from host
if [ -d "$host_ssh" ]; then
  rsync -r --delete "$host_ssh/" "$snap_ssh"
fi

# start ssh agent if it is not already running

ssh_env="$HOME/.ssh-env"

function load_ssh_env {
  . "${ssh_env}" > /dev/null
}

function start_agent {
  ssh-agent > "${ssh_env}"
  chmod 600 "${ssh_env}"
  load_ssh_env;
}

if [ -f "${ssh_env}" ]; then
  load_ssh_env;
  if ! ps "${SSH_AGENT_PID}" > /dev/null; then
    start_agent;
  fi
else
  start_agent;    
fi

export PATH="$SNAP/ssh-bin:$PATH"

exec "${@}"
