#!/bin/bash

REALHOME=$(getent passwd "$UID" | cut -d ':' -f 6)

host_gpg="$REALHOME/.gnupg"
snap_gpg="$HOME/.gnupg"

if [ -d "$snap_gpg" ]; then
    rm -rf "$snap_gpg"/*
else
    mkdir -m 0700 "$snap_gpg"
fi

if [ -d "$host_gpg" ]; then
    cp -r "$host_gpg"/* "$snap_gpg"
fi

rm -f "$snap_gpg"/S.*    # remove any sockets
rm -f "$snap_gpg"/*.conf # remove any config files

cd "$HOME/../current"
SNAP_CURRENT="$(pwd)"
GNUPGHOME="$SNAP_CURRENT/.gnupg"

cat > "$GNUPGHOME/gpg-agent.conf" <<EOM
homedir $GNUPGHOME
EOM

cat > "$GNUPGHOME/gpg.conf" <<EOM
homedir $GNUPGHOME
EOM

exec "${@}"
