#!/bin/bash

REALHOME=`getent passwd $UID | cut -d ':' -f 6`
PASSWORD_STORE="$SNAP_USER_COMMON/password-store"
CONFIG_DIR="$SNAP_USER_DATA/.config/gopass"
CONFIG_FILE="$CONFIG_DIR/config.yml"

# the home interface does not grant us access to dot-prefixed directories
# in REALHOME
mkdir -p "$PASSWORD_STORE"
if [ ! -f "$CONFIG_FILE" ]; then
  mkdir -p "$CONFIG_DIR"
  printf "%s\n" "root:" "  path: gpgcli-gitcli-fs+file://$PASSWORD_STORE" > "$CONFIG_FILE"
fi

ln -snf "$REALHOME/.gnupg" "$HOME/.gnupg"

if grep -q sss_ssh_knownhostsproxy /etc/ssh/ssh_config; then
  # ignore global SSH config because SSSD's known hosts config is not supported
  # by the ssh-keys interface
  export GIT_SSH_COMMAND="ssh -F $REALHOME/.ssh/config"
fi

exec "${@}"
