#!/bin/bash

function faketty() {
  script -qfc "export GPG_TTY=\$(tty); $(printf "%q " "$@")" /dev/null
}

# source the environment in which gpg was last called
. $HOME/.gpg-env

if [ "$XDG_SESSION_TYPE" = "tty" ] || [ -n "$FAKE_TTY" ]; then
  # pinentry-curses needs a tty
  faketty $SNAP/usr/bin/pinentry-curses
else
  $SNAP/usr/bin/pinentry-qt
fi
