#!/bin/bash

SSH_ENV=$HOME/.ssh-env

function start_agent {
  ssh-agent > "${SSH_ENV}"
  chmod 600 "${SSH_ENV}"
  . "${SSH_ENV}" > /dev/null
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
  . "${SSH_ENV}" > /dev/null
  ps "${SSH_AGENT_PID}" > /dev/null || {
    start_agent;
  }
else
  start_agent;    
fi

exec "${@}"
