#!/bin/bash

function can_open_file() {
  return $(head -c0 "$1" &> /dev/null);
}

function file_exists() {
  return $(stat "$1" &> /dev/null)
}

realhome=`getent passwd $UID | cut -d ':' -f 6`

# check the required interfaces (ssh-keys, gpg-keys) and tell user how to connect them
can_open_file /etc/ssh/ssh_config || ssh_keys_connected=false

gnupg_home="$realhome/.gnupg"
if file_exists "$gnupg_home" && ! can_open_file "$gnupg_home"; then
  gpg_keys_connected=false
fi

if [ "$ssh_keys_connected" = false ]; then
  printf "%s\n" \
  "Plug ssh-keys is not connected. This is required for syncing with git ssh remotes." \
  "To connect, run:" \
  "snap connect gopass:ssh-keys" ""
fi

if [ "$gpg_keys_connected" = false ]; then
  printf "%s\n" \
  "Plug gpg-keys is not connected. This is required for the default gpg crypto backend." \
  "To connect, run:" \
  "snap connect gopass:gpg-keys" ""
fi

if [ "$ssh_keys_connected" = false ] || [ "$gpg_keys_connected" = false ]; then
  exit 1
fi

# the home interface does not grant us access to dot-prefixed directories
# in REALHOME

if [ -z "$GOPASS_HOMEDIR" ]; then
  export GOPASS_HOMEDIR="$realhome/gopass"
  mkdir -p "$GOPASS_HOMEDIR"
fi

exec "${@}"
