name: gopass
base: core18
adopt-info: gopass
summary: The slightly more awesome Standard Unix Password Manager for Teams
description: | 
  gopass is a rewrite of the pass password manager in Go with the aim of making it 
  cross-platform and adding additional features. Our target audience are professional 
  developers and sysadmins (and especially teams of those) who are well versed with a 
  command line interface. One explicit goal for this project is to make it more approachable 
  to non-technical users. We go by the UNIX philosophy and try to do one thing and do it well, 
  providing a stellar user experience and a sane, simple interface.

grade: stable
confinement: strict
license: MIT

plugs:
  home: null
  gpg-keys: null
  ssh-keys: null # for git
  network-bind: null
  x11: null

apps:
  gopass:
    adapter: full
    command: bin/gopass
    command-chain:
      - bin/locales-launch
      - wrap-gopass
      - set-up-gnupg
      - set-up-ssh
      - fake-tty
    environment:
      FAKE_TTY: 1
      EDITOR: $SNAP/bin/nano

parts:      
  wrappers:
    plugin: dump
    source: snap/local/wrappers

  ssh:
    plugin: dump
    source: snap/local/ssh
    organize: 
      ssh: ssh-bin/
    stage-packages: 
      - openssh-client
      - util-linux
      - rsync

  gnupg:
    plugin: dump
    source: snap/local/gnupg
    stage-packages: 
      - gpg
      - gpg-agent
      - gpgconf
      - pinentry-curses
      - rsync

  locales-launch:
    plugin: nil
    stage-snaps: 
      - locales-launch
    stage-packages: 
      - libc-bin
      - locales

  gopass:
    plugin: go
    go-importpath: github.com/gopasspw/gopass
    source: https://github.com/gopasspw/gopass.git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --dirty)"
    override-build: |
      go build -ldflags "-X github.com/gopasspw/gopass/pkg/tempfile.globalPrefix=snap.gopass." -o gopass
      mkdir -p "$SNAPCRAFT_PART_INSTALL/bin"
      cp gopass "$SNAPCRAFT_PART_INSTALL/bin"
    build-packages: 
      - gcc
    stage-packages:
      - git
      - rng-tools
      - xsel
      - bsdutils
      - nano
  
layout:
  /etc/gnupg:
    bind: $SNAP/etc/gnupg
  /usr/bin/dirmngr:
    bind-file: $SNAP/usr/bin/dirmngr
  /usr/bin/gpg:
    bind-file: $SNAP/gpg
  /usr/bin/gpg-agent:
    bind-file: $SNAP/usr/bin/gpg-agent
  /usr/bin/gpg-connect-agent:
    bind-file: $SNAP/usr/bin/gpg-connect-agent
  /usr/bin/gpgconf:
    bind-file: $SNAP/usr/bin/gpgconf
  /usr/bin/pinentry:
    bind-file: $SNAP/usr/bin/pinentry-curses
  /usr/lib/gnupg:
    bind: $SNAP/usr/lib/gnupg
  /usr/share/gnupg:
    bind: $SNAP/usr/share/gnupg
  /etc/nanorc:
    bind-file: $SNAP/etc/nanorc
  /usr/share/nano:
    bind: $SNAP/usr/share/nano
