name: gopass
base: core18
version: "1.8.6"
summary: The slightly more awesome Standard Unix Password Manager for Teams
description: | 
  gopass is a rewrite of the pass password manager in Go with the aim of making it 
  cross-platform and adding additional features. Our target audience are professional 
  developers and sysadmins (and especially teams of those) who are well versed with a 
  command line interface. One explicit goal for this project is to make it more approachable 
  to non-technical users. We go by the UNIX philosophy and try to do one thing and do it well, 
  providing a stellar user experience and a sane, simple interface.

grade: stable
confinement: strict
license: MIT

plugs:
  home: null
  gpg-keys: null
  ssh-keys: null # for git
  network-bind: null
  x11: null
  desktop: null
  desktop-legacy: null
  wayland: null
  gsettings: null
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

environment:
  QT_QPA_PLATFORMTHEME: gtk3
  DISABLE_WAYLAND: 1

apps:
  gopass:
    adapter: full
    command: bin/gopass
    command-chain: &wrappers [bin/desktop-launch, wrap-gopass, set-up-gnupg, set-up-ssh]
  jsonapi:
    adapter: full
    command: bin/gopass jsonapi listen
    command-chain: *wrappers
  configure-firefox:
    command: xdg-desktop-portal-copy-file $SNAP/manifests/firefox-gopassbridge.json ~/
  configure-chrome:
    command: xdg-desktop-portal-copy-file $SNAP/manifests/chrome-gopassbridge.json

parts:
  qarma:
    plugin: nil
    stage-snaps: 
      - qarma/18
    stage:
      - usr/bin/qarma
    
  manifests:
    plugin: dump
    source: snap/local/manifests
    organize:
      '*': manifests/
  
  wrappers:
    plugin: dump
    source: snap/local/wrappers
  
  pinentry:
    plugin: dump
    source: snap/local/pinentry

  xdg-desktop-portal-copy-file:
    plugin: go
    go-importpath: github.com/ppd1990/xdg-desktop-portal-copy-file
    source: https://github.com/ppd1990/xdg-desktop-portal-copy-file.git
    
  gopass:
    plugin: go
    go-importpath: github.com/gopasspw/gopass
    source: https://github.com/gopasspw/gopass.git
    source-tag: "v1.8.6"
    build-packages:
      - gcc
    stage-packages:
      - git
      - rng-tools
      - xsel
      - gpg
      - gpg-agent
      - gpgconf
      - gpgsm
      - gpgv
      - pinentry-curses
      - pinentry-qt
      - bsdutils
      - openssh-client
      - rsync
    
  qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - qtwayland5
    
  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - qt5-gtk-platformtheme

layout:
  /etc/gnupg:
    bind: $SNAP/etc/gnupg
  /usr/bin/dirmngr:
    bind-file: $SNAP/usr/bin/dirmngr
  /usr/bin/gpg:
    bind-file: $SNAP/usr/bin/gpg
  /usr/bin/gpg-agent:
    bind-file: $SNAP/usr/bin/gpg-agent
  /usr/bin/gpg-connect-agent:
    bind-file: $SNAP/usr/bin/gpg-connect-agent
  /usr/bin/gpgconf:
    bind-file: $SNAP/usr/bin/gpgconf
  /usr/bin/gpgsm:
    bind-file: $SNAP/usr/bin/gpgsm
  /usr/bin/gpgv:
    bind-file: $SNAP/usr/bin/gpgv
  /usr/bin/pinentry:
    symlink: $SNAP/pinentry
  /usr/lib/gnupg:
    bind: $SNAP/usr/lib/gnupg
  /usr/share/gnupg:
    bind: $SNAP/usr/share/gnupg
