name: gopass
base: core18
version: "1.8.6"
summary: The slightly more awesome Standard Unix Password Manager for Teams
description: | 
  gopass is a rewrite of the pass password manager in Go with the aim of making it 
  cross-platform and adding additional features. Our target audience are professional 
  developers and sysadmins (and especially teams of those) who are well versed with a 
  command line interface. One explicit goal for this project is to make it more approachable 
  to non-technical users. We go by the UNIX philosophy and try to do one thing and do it well, 
  providing a stellar user experience and a sane, simple interface.
icon: logo.svg

grade: stable
confinement: strict
license: MIT

apps:
  gpg:
    command: bin/launch-gopass $SNAP/usr/bin/gpg
    plugs:
      - home
      - gpg-keys
      - gpg-public-keys
      - ssh-keys
  gopass:
    command: bin/launch-gopass $SNAP/bin/gopass
    plugs:
      - home
      - network
      - x11 # for xsel
      - gpg-keys # useless for this app so far, thus devmode
      - gpg-public-keys
      - ssh-keys # for git

parts:
  launchers:
    plugin: dump
    source: snap/local
    organize:
      'launch-gopass': bin/launch-gopass
  gnupg:
    plugin: autotools
    source: https://github.com/gpg/gnupg.git
    source-tag: gnupg-2.2.17
    configflags:
      - --prefix=/usr
      - --enable-maintainer-mode
      - --disable-doc
    override-build: |
      sed -i -E 's|"S.gpg-agent"|"S.gpg-agent.extra"|g' configure.ac
      ./autogen.sh
      snapcraftctl build
    build-packages:
      - libnpth0-dev
      - libgpg-error-dev
      - gettext
      - libgcrypt20-dev
      - libksba-dev
      - libassuan-dev
    stage-packages:
      - libassuan0
      - libksba8
      - libnpth0
  gopass:
    plugin: go
    go-importpath: github.com/gopasspw/gopass
    source: https://github.com/gopasspw/gopass.git
    source-tag: "v1.8.6"
    build-packages:
      - gcc
    stage-packages:
      - git
      - rng-tools
      - xsel
